#!/usr/bin/env bash
# install nginx web server to listen on port 80

sudo apt-get update
sudo apt-get -y install nginx
# Listen on port 80
sudo ufw allow 'Nginx HTTP'
# create string Hello World and start nginx
touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
