#!/usr/bin/env bash
# install nginx web server to listen on port 80

sudo apt-get update
sudo apt-get -y install nginx
# Listen on port 80 and set redirection
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx start
