#!/usr/bin/env bash
# install nginx web server to listen on port 80

sudo apt-get update
sudo apt-get -y install nginx
# Listen on port 80
sudo ufw allow 'Nginx HTTP'
# create string Hello World and start nginx
touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html
# redirection
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
# not found
touch /var/www/html/custom_404.html && echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i '/listen 80 default_server;/ a \\terror_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo service nginx start
