#!/usr/bin/env bash
# Installs Nginx and configures the server.

apt-get update
apt-get -y install nginx
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
cp new_default /etc/nginx/sites-available/default
sed -i 's/# server_names_hash_bucket_size 64;/server_names_hash_bucket_size 64;/' /etc/nginx/nginx.conf
cp new_default_1 /etc/nginx/sites-available/default
nginx -t
sudo /etc/init.d/nginx restart
