#!/usr/bin/env bash
# displays the PID, along with the process name, of processes whose name contain the word bash.
trap "echo 'I am invincible!!!'" SIGTERM
while true; do
  echo 'To infinity and beyond'
    sleep 2
    done
