#!/usr/bin/env bash
# This script prints "bad luck" and "good luck" on the 4th and 8th iterations
# respectively, and "best school" on the remaining 8 iterations.

i="0"

while [ $i -lt 10 ]
do
    if [ $i -eq 3 ]
    then
	echo "bad luck"
    elif [ $i -eq 7 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi

    i=$((i + 1))
done
