#!/usr/bin/env bash
# This script display numbers from 1 to 20 but displays some text after the
# numbers 4, 9 and 17

i="1"

while [ $i -lt 21 ]
do
    echo "$i"
    case $i in
	"4") echo "bad luck from China";;
	"9") echo "bad luck from Japan";;
	"17") echo "bad luck from Italy";;
    esac
    ((i++))

done
